### ISSUE TITLE
Not able to send SMS via custom gateway

### ISSUE THREAD

**Issue by clickervinod** [softon/sms#12]
This is my code and configuration, im not able to send SMS via custom gateway.
where i am wrong.
 "softon/sms": "2.0.2",

config/sms.php

`
    'bhas' => [                           // Can be used for any gateway
        'url' => 'http://mysms.clickerstudio.in/api/sendmsg.php?',                        // Gateway Endpoint
        'params' => [                       // Parameters to be included in the request
            'send_to_name' => 'mobile',           // Name of the field of recipient number
            'msg_name' => 'message',               // Name of the field of Message Text
            'others' => [                   // Other Authentication params with their values
                'user' => 'myusername',
                'pass' => 'dsjofkjh',
                'sender' => 'TECARE',
                'priority' => 'ndnd',
                'stype' => 'normal',
            ],
        ],
        'add_code' => false,                 // Append country code to the mobile numbers
    ],`

**Comment by softon** [comment]
sorry for the late reply. that is not how u use it. you have to replace the variables name with your own for like send_to_name,msg_name etc. if the problem is still not resolved pls post the actual config and the calling function used. thank you.

**Comment by clickervinod** [comment]
Hi,
Thanks for reply i have fixed the issue there was a problem of different key name mobile - phone in config file
