### ISSUE TITLE
Class Softon\Sms\Gateways\customGateway does not exist

### ISSUE THREAD

**Issue by ahmedelhadi** [softon/sms#4]
Dear Softon Author ,

hope all going fine , this issue appear in live version  "Class Softon\Sms\Gateways\customGateway does not exist" , but in laravel homestead working fine  

Laravel 5.2

**Comment by softon** [comment]
Need more info to solve the problem if its still there.

**Comment by kumarravisingh** [comment]
I am having the same issue on live, everything works find on dev server, what Info do you need?

**Comment by j33tmane** [comment]
i have gone through the same issue..
The thing is on live server if there is a case sensitive file system, you wll get this error.
So u need to perform small change in vendor\softon\sms\src\SmsServiceProvider.php
below line no.22 put this..
if($gateway=='custom')
 $gateway = 'Custom';
