### ISSUE TITLE
ERR: 108, Invalid or missing api_id

### ISSUE THREAD

**Issue by diyahnf** [softon/sms#5]
Dear Softon Author,

I'm using Clickatell. I'm sure i have used the correct API Key but I still get this error response:
"ERR: 108, Invalid or missing api_id"

What is actually the api_id, isn't it the API Key that generate under SMS Integration menu?
Thanks.

![capture](https://cloud.githubusercontent.com/assets/11990696/21210806/cd1b27ee-c2b0-11e6-870a-9958754ade93.PNG)

**Comment by softon** [comment]
You must not have copied the api key correctly. Or u can reset and create a new integration key if the problem still exists.
