### ISSUE TITLE
how to call clickatell SMS API using softon

### ISSUE THREAD

**Issue by maulikkanani1** [softon/sms#7]
i new in clickatell. so, i dont know how to send message using clickatell SMS API.
i follow hole step but i don't know which file i put this line:
**//Gateways ::  Log / Clickatell / Gupshup / MVaayoo / SmsAchariya / SmsCountry / SmsLane / Custom
Sms::gateway('NameOfGateway')->send(['87686655455','1212121212','2323232323'],'sms.test',['param1'=>'Name 1']);**
and also in which parameter pass on this array ['param1'=>'Name 1']

**Comment by gr8shivam** [comment]
Give this a try: https://packagist.org/packages/gr8shivam/laravel-sms-api

**Comment by softon** [comment]
NameOfGateway for you will be Clickatell

Params are optional. If you want to send any parameters to the sms view to be displayed
