### ISSUE TITLE
Laravel 5.5 Support ???

### ISSUE THREAD

**Issue by salahy2** [softon/sms#8]
I am getting error when using it in Laravel 5.5 same code worked perfectly on 5.2

`Target [Softon\Sms\Gateways\SmsGatewayInterface] is not instantiable while building [\Softon\Sms\Sms].`

**Comment by ghost** [comment]
@softon I am getting the same error in L5.4 also.

**Comment by ghost** [comment]
@softon @salahy2  I tried to edit the `SmsServiceProvider.php` file as given below - 


        $this->app->bind('sms', 'Softon\Sms\Sms');

        $this->app->bind('Softon\Sms\Gateways\SmsGatewayInterface','Softon\Sms\Gateways\\'.$gateway.'Gateway');
        $this->app->bind('Softon\Sms\SmsViewInterface','Softon\Sms\Sms'.$view.'View');

here I have removed the initial backslash `\`from the namespace and it started working.

**Comment by gr8shivam** [comment]
Give this a try: https://packagist.org/packages/gr8shivam/laravel-sms-api

**Comment by musamamasood** [comment]
Hello, 
I am getting same message with L5.5. Is there any official solution for it?

**Comment by gr8shivam** [comment]
Hi @musamamasood , would suggest you to try (https://github.com/gr8shivam/laravel-sms-api). If the issue arises with that too, just raise an issue here (https://github.com/gr8shivam/laravel-sms-api) and I would love to resolve that.

**Comment by musamamasood** [comment]
Is it possible that I can use multiple custom gateway? Also is it possible to setup blade template for multiple sms message?

Thanks.

**Comment by gr8shivam** [comment]
1. Multiple Custom Gateways: Yes, you can configure them easily.
2. Blade Template: Well not exactly in a blade template as it ain't required for a small message. Though you can use pre-defined notification templates to achieve the same use case.

**Comment by musamamasood** [comment]
Thanks.
